---
title: "Alumni Survey Bounce and Open Rate"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_lib, warning=FALSE}
library(data.table)
library(tidyverse)
library(stargazer)
library(sandwich)
library(lmtest)
library(AER) # for IV regression
```

## Load Data
```{r load_data}
# list of people
dt_roster <- read_csv('data/alumni_scrape.csv', col_types=cols()) %>%
  select(Email = email, Gender = gender, Year_Graduation = year_graduation, 
         Block = blocking_genderyear_assignments) %>% 
  mutate(Block = ifelse(
    Block == 1, "Direct", ifelse(
      Block == 2, "Philanthropic", "Control")))

# attrition, bounced, round 1 post-send merged status
r1_g1_bounce <- read_csv('data/round1_0702_group1_0702_0941.csv', col_types=cols()) %>%
  select(Email, MStatus = `Merge status`) %>%
  filter(MStatus == 'BOUNCED')
r1_g2_bounce <- read_csv('data/round1_0702_group2_0702_1028.csv', col_types=cols()) %>%
  select(Email, MStatus = `Merge status`) %>%
  filter(MStatus == 'BOUNCED')
r1_g3_bounce <- read_csv('data/round1_0702_group3_0702_1055.csv', col_types=cols()) %>%
  select(Email, MStatus = `Merge status`) %>%
  filter(MStatus == 'BOUNCED')

# final status, sent, opened
r1_g1_status <- read_csv('data/round1_0702_group1_0708_1033.csv', col_types=cols()) %>%
  select(Email, MStatus = `Merge status`) 
r1_g2_status <- read_csv('data/round1_0702_group2_0708_1220.csv', col_types=cols()) %>%
  select(Email, MStatus = `Merge status`) 
r1_g3_status <- read_csv('data/round1_0702_group3_0708_1122.csv', col_types=cols()) %>%
  select(Email, MStatus = `Merge status`) 
r2_status <- read_csv('data/round2_0709_all_0716_1117.csv', col_types=cols()) %>%
  select(Email, MStatus = `Merge status`) 
r3_status <- read_csv('data/round3_0716_all_0722_1046.csv', col_types=cols()) %>%
  select(Email, MStatus = `Merge status`) 
r4_status <- read_csv('data/round4_0722_all_0723_1131.csv', col_types=cols()) %>%
  select(Email, MStatus = `Merge status`) 
r5_status <- read_csv('data/round5_0723_all_0724_1219.csv', col_types=cols()) %>%
  select(Email, MStatus = `Merge status`) 

# outcome, Qualtrics completion
dt_qualtrics <- read_csv('data/Qualtrics_downloaded_20210726.csv', col_types=cols()) %>%
  select(Email = RecipientEmail, Duration = `Duration (in seconds)`,
         Long = LocationLongitude, Lat = LocationLatitude) %>%
  slice(3:n()) %>%
  mutate(Duration = as.numeric(Duration),
         Long = as.numeric(Long),
         Lat = as.numeric(Lat))

# emails to exclude
ex_emails <- c('deveshkhandelwal@berkeley.edu', 'rahosbach@berkeley.edu',
               'tgao2020@berkeley.edu', 'tgao2020@berkely.edu',
               'mirza2020@berkeley.edu')
```

## Combine Data
```{r combine_data}

dt_agg <- 
  # roster does not contain us
  dt_roster %>%
  select(Email) %>%
  
  # bounce
  left_join(bind_rows(r1_g1_bounce, r1_g2_bounce, r1_g3_bounce) %>%
              add_column(bounce = 1) %>%
              select(-MStatus),
            by = 'Email') %>%
  replace(is.na(.), 0) %>%
  
  # non-compliance: email_sent status for all 5 rounds
  left_join(
    # EMAIL_SENT not balanced.
    #bind_rows(r1_g1_status %>% filter(MStatus == 'EMAIL_SENT'),
    #          r1_g2_status %>% filter(MStatus == 'EMAIL_SENT'),
    #          r1_g3_status %>% filter(MStatus == 'EMAIL_SENT')) %>%
    #  filter(!Email %in% ex_emails) %>%
    #inner_join(r2_status %>% filter(MStatus == 'EMAIL_SENT') %>% select(Email), 
    #           by='Email') %>%
    
    # EMAIL_SENT is balanced in r3, r4 and r5
    dt_roster %>% select(Email) %>% add_column(MStatus='EMAIL_SENT') %>%
      
      inner_join(r3_status %>% filter(MStatus == 'EMAIL_SENT') %>% select(Email), 
                 by='Email') %>%
      inner_join(r4_status %>% filter(MStatus == 'EMAIL_SENT') %>% select(Email), 
                 by='Email') %>% # 4 & 5 are the same?
      inner_join(r5_status %>% filter(MStatus == 'EMAIL_SENT') %>% select(Email), 
                 by='Email') %>%
      add_column(non_complier = 1) %>%
      select(-MStatus),
    by = 'Email') %>%
  replace(is.na(.), 0) %>%
  
  # compliers: people who opened at least 1 round
  mutate(complier = 1 - (bounce + non_complier)) %>%
  
  # completion: qualtrics records
  left_join(dt_qualtrics %>% select(Email) %>% add_column(completion=1), by = 'Email') %>%
  replace(is.na(.), 0) %>%
  
  # override some incorrect YAMM data
  # (these two lines correct rows for 4 people, all in the philanthropic group)
  # vishal, ansjory, taeil.goh, and davidhou
  mutate(non_complier = if_else(completion == 1, 0, non_complier),
         complier = if_else(completion == 1, 1, complier)) %>% 
  
  # meta data
  left_join(dt_roster, by = 'Email') %>%
  left_join(dt_qualtrics, by = 'Email') 

```

## Output Data
```{r output}
# output
write_csv(dt_agg, 'data/agg_table.csv')
```

## Covariance Balance Check
```{r cov_balance}
dt_agg %>% 
  select(Block, bounce, non_complier, complier, completion) %>%
  gather(measure, value, -Block) %>%
  group_by(Block, measure) %>%
  summarise(value = sum(value)) %>%
  spread(measure, value) %>%
  select(Block, bounce, non_complier, complier, completion) %>%
  mutate(all = bounce + non_complier + complier, .before=2)

dt_agg %>% 
  select(Block, bounce, non_complier, complier, completion) %>%
  gather(measure, value, -Block) %>%
  group_by(Block, measure) %>%
  summarise(value = sum(value)) %>%
  ungroup() %>%
  filter(measure != 'completion') %>%
  mutate(measure = recode_factor(measure, 
                                 bounce = "Email Bounced (Attrition)", 
                                 non_complier = 'Did Not Open (Non-Complier)',
                                 complier = "Opened Email (Complier)")) %>%
  # plotting
  ggplot(aes(x=Block, y=value, fill=measure)) +
  geom_col() +
  labs(x='Treatment Group', y='Count', title='Covariate Balance Check',
       fill='Status') +
  scale_fill_brewer(palette = 'Accent') +
  theme_bw()

dt_cb <- dt_agg %>% 
  select(Block, bounce, non_complier, complier, completion)  %>%
  data.table()

cb1 <- dt_cb[, lm(bounce~Block)]
cb2 <- dt_cb[, lm(non_complier~Block)]
cb3 <- dt_cb[, lm(complier~Block)]

stargazer(cb1, cb2, cb3, summary = FALSE, header = FALSE, 
          title = "Covariate Balance Check",
          digits = 3,
          type="text",
          covariate.labels = c("Group: Direct", 
                               "Group: Philanthropic",
                               "Constant"),
          dep.var.labels = c("Attrition", 'Non-Compliance', 'Compliance'))


```

## ITT Models
```{r itt}
# Convert dt_agg to a data.table
d <- data.table(dt_agg)
head(d)

# Generate models
m1 <- d[bounce == 0 , lm(completion ~ Block)]
m2 <- d[bounce == 0 , lm(completion ~ Block + Gender + factor(Year_Graduation))]

summary(m2)


# Calculate robust SEs for both models
rse1 <- sqrt(diag(vcovHC(m1)))
rse2 <- sqrt(diag(vcovHC(m2)))

# Generate stargazer table
stargazer(m1, m2, summary = FALSE, header = FALSE, 
          title = "ITT Estimate with Attriters Removed",
          digits = 3,
          type="text",
          se = list(rse1, rse2),
          covariate.labels = c("Group: Direct", "Group: Philanthropic",
                               "Gender: Male", "Gender: Unknown",
                               "Cohort: 2016", "Cohort: 2017",
                               "Cohort: 2018", "Cohort: 2019",
                               "Cohort: 2020", "Cohort: 2021",
                               "Constant"),
          dep.var.labels = "Survey Completion")


```

```{r Heterogenous Treatment effect}

# HTE between grad year and treatment
m3 <- d[bounce == 0 , lm(completion ~ Block +  factor(Year_Graduation) + Block*factor(Year_Graduation))]
rse3 <- sqrt(diag(vcovHC(m3 ,type = "HC1")))




m4 <- d[bounce == 0 , lm(completion ~ Block +  Gender + Block*Gender)]
rse4 <- sqrt(diag(vcovHC(m4 ,type = "HC1")))




collist_m3 = c("Group: Direct", "Group: Philanthropic", "Cohort:2016","Cohort:2017","Cohort:2018","Cohort:2019","Cohort:2020","Cohort:2021" ,"Direct:Cohort:2016","Phil:Cohort:2016","Direct:Cohort:2016","Phil:Cohort:2016","Direct:Cohort:2017","Phil:Cohort:2017","Direct:Cohort:2018","Phil:Cohort:2018","Direct:Cohort:2019","Phil:Cohort:2019","Direct:Cohort:2020","Phil:Cohort:2020","Direct:Cohort:2021","Phil:Cohort:2021")

collist_m4 = c("Group: Direct", "Group: Philanthropic","Gender:Male","Gender:Unk","Direct:Male", "Phil:Male","Direct:Unk","Phil:Unk")




stargazer(m3,m4,summary = FALSE, header = FALSE,
          title = "HTE between Gender , Graduation Year and Tretment",
          se = list(rse3, rse4),
          type = "text",
          covariate.labels = c(collist_m3,collist_m4 ),
          dep.var.labels = "Survey Completion")






```



## CACE Models
```{r cace}
# Calculate the CACE for each treatment group manually
ittd_direct <- (d[bounce == 0 & Block == "Direct" & complier == 1, .N] /
                  d[bounce == 0 & Block == "Direct" , .N])
ittd_philanthropic <- (d[bounce == 0 & Block == "Philanthropic" & complier == 1, .N] /
                         d[bounce == 0 & Block == "Philanthropic" , .N])
cace_direct <- m2$coefficients[2] / ittd_direct
cace_philanthropic <- m2$coefficients[3] / ittd_philanthropic

ittd_regress <- d[ , lm(completion ~ Block)]
coeftest(ittd_regress,vcovHC(ittd_regress))



#summary(ittd_regress)

# Generate IV regression models
d[ , treated := complier * (Block != "Control")]
ivmod_direct <- d[bounce == 0 & Block != "Philanthropic",
                  ivreg(completion ~ treated | Block)]
ivmod_philanthropic <- d[bounce == 0 & Block != "Direct",
                         ivreg(completion ~ treated | Block)]

# Calculate robust SEs for the IV regression models
rseiv_direct <- sqrt(diag(vcovHC(ivmod_direct)))
rseiv_philanthropic <- sqrt(diag(vcovHC(ivmod_philanthropic)))

# Generate stargazer table
stargazer(ivmod_direct, ivmod_philanthropic, summary = FALSE, header = FALSE, 
          title = "CACE Estimate with Attriters Removed",
          digits = 3,
          type="text",
          se = list(rseiv_direct, rseiv_philanthropic),
          dep.var.labels = "Survey Completion",
          column.labels = c("Direct", "Philanthropic"))
```